outdir        : "arabidopsis"
genome        : "/core/cbc/tutorials/workshopdirs/Structural-Annotation-Version3/results/02_mask_repeats/repeatmasker/repeatmasker_out/GCF_000001735.4_TAIR10.1_genomic.fna.masked"
user_reads    : "/core/cbc/tutorials/workshopdirs/Structural-Annotation-Version3/data/rnaseq/*{1,2}.fastq"
busco_lineage : "embryophyta"
order         : "Brassicales"
prefix        : "arabidopsis"
reference_db  : "/isg/shared/databases/Diamond/RefSeq/plant.protein.faa.208.dmnd"
taxon         : "arabidopsis"
external_protein : "true"
