outdir       : "arabidopsis"
genome       : "/core/cbc/tutorials/workshopdirs/Structural-Annotation-Version3/data/genome/GCF_000001735.4_TAIR10.1_genomic.fna"
user_reads   : "/core/cbc/tutorials/workshopdirs/Structural-Annotation-Version3/data/rnaseq/*{1,2}.fastq"
orthoDB      : "embryophyta"
order        : "Brassicales"
prefix       : "arabidopsis"
reference_db : "/isg/shared/databases/Diamond/RefSeq/plant.protein.faa.208.dmnd"
taxon        : "arabidopsis"
